name: Example Controlled Events
on:
  pull_request: 
    types:
      - opened
      - closed
  workflow_dispatch:
jobs:
  Events_test:
    runs-on: self-hosted
    steps:
      - name: Controlled Event Testing
        run: |
            echo "Controlled Event Testing"
            echo "Done!...."
