name: Azure Terraform deployment
on:
  push:
    branches:
      - azure_rg_create
jobs:
  deploy:
    name: Azure RG deployment using GitHub Action and Terraform
    runs-on: self-hosted  # or self-hosted if you have your own runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        working-directory: azure_resource_group_create/01_rg
        run: terraform init

      - name: Terraform Plan
        working-directory: azure_resource_group_create/01_rg
        run: terraform plan

      - name: Terraform Apply
        working-directory: azure_resource_group_create/01_rg
        run: terraform apply -auto-approve
