name: Azure Terraform deployment

on:
  push:
    branches:
      - azure_rg_create
      - azure_rg_destroy
  workflow_dispatch:

jobs:
  deploy:
    name: Azure RG deployment using GitHub Action and Terraform
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run terraform per folder
        run: |
          # List all Terraform folders explicitly
          folders="azure_resource_group/01 azure_resource_group/02 azure_resource_group/03"

          echo "Current branch: $GITHUB_REF"
          echo "Folders to process: $folders"

          for folder in $folders; do
            if [ ! -d "$folder" ]; then
              echo "Directory $folder does not exist; skipping."
              continue
            fi

            echo "Processing folder: $folder"

            cd "$folder" || { echo "Failed to enter directory $folder"; exit 1; }

            echo "Running terraform init in $folder"
            terraform init

            echo "Running terraform plan in $folder"
            terraform plan

            if [[ "$GITHUB_REF" == "refs/heads/azure_rg_create" ]]; then
              echo "Running terraform apply in $folder"
              terraform apply -auto-approve
            elif [[ "$GITHUB_REF" == "refs/heads/azure_rg_destroy" ]]; then
              echo "Running terraform destroy in $folder"
              terraform destroy -auto-approve
            else
              echo "Branch $GITHUB_REF does not trigger apply or destroy."
            fi

            cd - > /dev/null
          done