name: Azure Terraform deployment

on:
  push:
    branches:
      - azure_rg_create
      - azure_rg_destroy
  workflow_dispatch:

jobs:
  deploy:
    name: Azure RG deployment using GitHub Action and Terraform
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set folders to process
        id: set-folders
        run: |
          # Hardcode folders here (or list dynamically if you want all folders)
          folders="azure_resource_group_create/01_rg,azure_resource_group_create/02_rg,azure_resource_group_create/03_rg"
          echo "folders=$folders" >> $GITHUB_OUTPUT
      - name: Run terraform per folder
        run: |
          folders="${{ steps.set-folders.outputs.folders }}"
          echo "Current branch: $GITHUB_REF"
          echo "Folders to process: $folders"
          if [ -z "$folders" ]; then
            echo "No folders specified; exiting."
            exit 0
          fi
          IFS=',' read -ra DIRS <<< "$folders"
          for dir in "${DIRS[@]}"; do
            folder=$(echo "$dir" | sed 's:/*$::')
            echo "Processing folder: $folder"
            if [ ! -d "$folder" ]; then
              echo "Directory $folder does not exist; skipping."
              continue
            fi
            cd "$folder" || { echo "Failed to cd into $folder"; exit 1; }
            echo "Running terraform init in $folder"
            terraform init
            echo "Running terraform plan in $folder"
            terraform plan
            if [[ "$GITHUB_REF" == "refs/heads/azure_rg_create" ]]; then
              echo "Running terraform apply in $folder"
              terraform apply -auto-approve
            elif [[ "$GITHUB_REF" == "refs/heads/azure_gr_destroy" ]]; then
              echo "Running terraform destroy in $folder"
              terraform destroy -auto-approve
            else
              echo "Branch $GITHUB_REF does not trigger apply or destroy."
            fi
            cd - > /dev/null
          done