name: Azure Terraform deployment
on:
  push:
    branches:
      - azure_rg_create
      - azure_gr_destory
jobs:
  deploy:
    name: Azure RG deployment using GitHub Action and Terraform
    runs-on: self-hosted  # or self-hosted if you have your own runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        working-directory: azure_resource_group_create/01_rg
        run: terraform init

      - name: Terraform Plan
        working-directory: azure_resource_group_create/01_rg
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/azure_gr_create'
        working-directory: azure_resource_group_create/01_rg
        run: terraform apply -auto-approve

      - name: Terraform Destory
        if: github.ref == 'refs/heads/azure_gr_destory'
        working-directory: azure_resource_group_create/01_rg
        run: terraform destory -auto-approve

#Usage and details:
#Push commits to the branch azure_rg_create to create/update the resource group.

#Push commits (or even an empty commit) to the branch azure_rg_destroy to destroy the resources.